apiVersion: v1
kind: Service
metadata:
  name: restaurants-db
  labels:
    app: restaurants-db
spec:
  clusterIP: None
  selector:
    app: restaurants-db
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo
