apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  PORT: "8080"
  JWT_ISSUER: user-service
  JWT_PUBLIC_KEY_PATH: /run/jwt/jwt.pub
  DEFAULT_PAYMENT_METHOD: mock-card
  LOG_LEVEL: info
