apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  LOG_LEVEL: warn
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-service-config
data:
  LOG_LEVEL: warn
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  LOG_LEVEL: warn
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  LOG_LEVEL: warn
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatch-service-config
data:
  LOG_LEVEL: warn
