apiVersion: v1
kind: Service
metadata:
  name: dispatch-service
  labels:
    app: dispatch-service
spec:
  selector:
    app: dispatch-service
  ports:
    - name: http
      port: 8080
      targetPort: http
