apiVersion: v1
kind: Service
metadata:
  name: payments-db
  labels:
    app: payments-db
spec:
  clusterIP: None
  selector:
    app: payments-db
  ports:
    - name: pg
      port: 5432
      targetPort: pg
    - name: metrics
      port: 9187
      targetPort: metrics
