apiVersion: v1
kind: Service
metadata:
  name: orders-cache
  labels:
    app: orders-cache
spec:
  selector:
    app: orders-cache
  ports:
    - name: redis
      port: 6379
      targetPort: redis
    - name: metrics
      port: 9121
      targetPort: metrics
